"""drop sandbox_provider from user_settings

Revision ID: b7fae3df7bca
Revises: 671ba6b1f752
Create Date: 2026-04-22 23:47:10.858160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7fae3df7bca'
down_revision: Union[str, None] = '671ba6b1f752'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_settings', 'sandbox_provider')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_settings', sa.Column('sandbox_provider', sa.VARCHAR(length=32), server_default=sa.text("'docker'::character varying"), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
